# Generated by Django 4.2.7 on 2025-11-02 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True, verbose_name='이메일')),
                ('username', models.CharField(db_column='username', max_length=100, unique=True, verbose_name='사용자명')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('viewer', 'Viewer')], db_column='role', default='viewer', max_length=20, verbose_name='역할')),
                ('department', models.CharField(blank=True, db_column='department', max_length=100, null=True, verbose_name='부서')),
                ('is_active', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], db_column='is_active', default='pending', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자들',
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
